"""Compatibility shim. Implementation lives in ``knowledge_core.gemini_backend``."""

from knowledge_core.gemini_backend import (
    DEVELOPER_API_KEY_ENV_NAMES,
    EVAL_API_KEY_ENV_NAMES,
    GEMINI_DOTENV_KEY_NAMES,
    GOOGLE_GENAI_PROVIDER,
    UNAPPROVED_VERTEX_LOCATION_PLACEHOLDER,
    GeminiApiBackend,
    GeminiBackendConfig,
    GeminiConfigurationError,
    apply_gemini_sdk_env_flags,
    assert_vertex_process_has_no_api_keys,
    developer_api_key_available,
    file_search_supported,
    is_google_genai_model,
    load_dotenv_for_gemini_backend,
    parse_gemini_api_backend,
    peek_gemini_api_backend,
    present_developer_api_key_names,
    require_developer_api_for_file_search,
    require_developer_api_key,
    reset_gemini_backend_for_tests,
    resolve_gemini_backend,
    strip_model_provider,
)

__all__ = [
    "DEVELOPER_API_KEY_ENV_NAMES",
    "EVAL_API_KEY_ENV_NAMES",
    "GEMINI_DOTENV_KEY_NAMES",
    "GOOGLE_GENAI_PROVIDER",
    "UNAPPROVED_VERTEX_LOCATION_PLACEHOLDER",
    "GeminiApiBackend",
    "GeminiBackendConfig",
    "GeminiConfigurationError",
    "apply_gemini_sdk_env_flags",
    "assert_vertex_process_has_no_api_keys",
    "developer_api_key_available",
    "file_search_supported",
    "is_google_genai_model",
    "load_dotenv_for_gemini_backend",
    "parse_gemini_api_backend",
    "peek_gemini_api_backend",
    "present_developer_api_key_names",
    "require_developer_api_for_file_search",
    "require_developer_api_key",
    "reset_gemini_backend_for_tests",
    "resolve_gemini_backend",
    "strip_model_provider",
]
