/** Type definitions for Console V2 APIs and entities */

// Prefer the OpenAPI-generated contract for shared work/workflow and workbench shapes.
export type {
  EvidenceRef,
  WorkItem,
  WorkItemAction,
  WorkItemsResponse,
  WorkSummaryResponse,
  WorkflowDetailResponse,
  WorkflowStage,
  FaqItem,
  ItTicketItem,
  CitationItem,
  ChatMessage,
  ConversationDetail,
  DashboardKpiMetrics,
  SpikeAlertItem,
  TopFrequentTopic,
  KnowledgeBlindSpot,
  KnowledgeGapItem,
  ChunkQualityIssue,
  ChunkQualitySummary,
  ManualChunkImage,
  ManualChunkItem,
  ManualDocumentItem,
  IngestionStage,
  ChunkingProfile,
  OverviewApiResponse,
  PortalImportResult,
  PortalDocumentRecord,
  PortalDocumentList,
  PortalDocumentDetail,
  PendingPortalReviewList,
  ChunkPreviewResponse,
} from './generated/backoffice-schemas';
